# Generated by Django 5.2.4 on 2025-07-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код диагноза (МКБ-10)')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование диагноза')),
            ],
            options={
                'verbose_name': 'Диагноз',
                'verbose_name_plural': 'Диагнозы',
                'ordering': ['code'],
            },
        ),
    ]
