# Generated by Django 5.2.4 on 2025-08-23 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('departments', '0002_initial'),
        ('encounters', '0010_remove_treatment_models'),
        ('instrumental_procedures', '0002_initial'),
        ('lab_tests', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('paused', 'Приостановлено'), ('rejected', 'Забраковано')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Укажите причину отмены назначения', verbose_name='Причина отмены')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата приостановки')),
                ('pause_reason', models.TextField(blank=True, help_text='Укажите причину приостановки назначения', verbose_name='Причина приостановки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('completion_notes', models.TextField(blank=True, verbose_name='Примечания к завершению')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название плана')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('priority', models.CharField(choices=[('normal', 'Обычный'), ('urgent', 'Срочный'), ('emergency', 'Экстренный')], default='normal', max_length=20, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='Отменил')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_completed', to=settings.AUTH_USER_MODEL, verbose_name='Завершил')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель плана')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examination_plans', to='encounters.encounter', verbose_name='Случай обращения')),
                ('patient_department_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examination_plans', to='departments.patientdepartmentstatus', verbose_name='Статус пациента в отделении')),
                ('paused_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_paused', to=settings.AUTH_USER_MODEL, verbose_name='Приостановил')),
            ],
            options={
                'verbose_name': 'План обследования',
                'verbose_name_plural': 'Планы обследования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationLabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('paused', 'Приостановлено'), ('rejected', 'Забраковано')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Укажите причину отмены назначения', verbose_name='Причина отмены')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата приостановки')),
                ('pause_reason', models.TextField(blank=True, help_text='Укажите причину приостановки назначения', verbose_name='Причина приостановки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('completion_notes', models.TextField(blank=True, verbose_name='Примечания к завершению')),
                ('instructions', models.TextField(blank=True, verbose_name='Особые указания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='Отменил')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_completed', to=settings.AUTH_USER_MODEL, verbose_name='Завершил')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_lab_tests', to='lab_tests.labtestdefinition', verbose_name='Лабораторное исследование')),
                ('paused_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_paused', to=settings.AUTH_USER_MODEL, verbose_name='Приостановил')),
                ('examination_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='examination_management.examinationplan', verbose_name='План обследования')),
            ],
            options={
                'verbose_name': 'Лабораторное исследование в плане',
                'verbose_name_plural': 'Лабораторные исследования в плане',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationInstrumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('paused', 'Приостановлено'), ('rejected', 'Забраковано')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Укажите причину отмены назначения', verbose_name='Причина отмены')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата приостановки')),
                ('pause_reason', models.TextField(blank=True, help_text='Укажите причину приостановки назначения', verbose_name='Причина приостановки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('completion_notes', models.TextField(blank=True, verbose_name='Примечания к завершению')),
                ('instructions', models.TextField(blank=True, verbose_name='Особые указания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='Отменил')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_completed', to=settings.AUTH_USER_MODEL, verbose_name='Завершил')),
                ('instrumental_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_instrumentals', to='instrumental_procedures.instrumentalproceduredefinition', verbose_name='Инструментальное исследование')),
                ('paused_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_paused', to=settings.AUTH_USER_MODEL, verbose_name='Приостановил')),
                ('examination_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumental_procedures', to='examination_management.examinationplan', verbose_name='План обследования')),
            ],
            options={
                'verbose_name': 'Инструментальное исследование в плане',
                'verbose_name_plural': 'Инструментальные исследования в плане',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='examinationplan',
            index=models.Index(fields=['patient_department_status', 'created_at'], name='examination_patient_ac461d_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationplan',
            index=models.Index(fields=['encounter', 'created_at'], name='examination_encount_289891_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationplan',
            index=models.Index(fields=['content_type', 'object_id', 'created_at'], name='examination_content_0d3ce8_idx'),
        ),
    ]
