# Generated by Django 5.2.4 on 2025-08-15 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0009_remove_examinationlabtest_examination_plan_and_more'),
        ('instrumental_procedures', '0002_initial'),
        # ('treatment_assignments', '0002_remove_medicationassignment_dosing_rule'),  # УДАЛЕНО
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название плана')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('priority', models.CharField(choices=[('normal', 'Обычный'), ('urgent', 'Срочный'), ('emergency', 'Экстренный')], default='normal', max_length=20, verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_plans', to='encounters.encounter', verbose_name='Случай обращения')),
            ],
            options={
                'verbose_name': 'План обследования',
                'verbose_name_plural': 'Планы обследования',
                'ordering': ['-created_at'],
            },
        ),
        # migrations.CreateModel(  # УДАЛЕНО - ссылается на несуществующую модель
        #     name='ExaminationLabTest',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
        #         ('instructions', models.TextField(blank=True, verbose_name='Особые указания')),
        #         ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
        #         ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
        #         ('lab_test_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_lab_tests', to='treatment_assignments.labtestassignment', verbose_name='Назначение лабораторного исследования')),
        #         ('examination_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='examination_management.examinationplan', verbose_name='План обследования')),
        #     ],
        #     options={
        #         'verbose_name': 'Лабораторное исследование в плане',
        #         'verbose_name_plural': 'Лабораторные исследования в плане',
        #         'ordering': ['-created_at'],
        #     },
        # ),
        migrations.CreateModel(
            name='ExaminationInstrumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('instructions', models.TextField(blank=True, verbose_name='Особые указания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('procedure_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumental_procedures.instrumentalproceduredefinition', verbose_name='Определение процедуры')),
                ('examination_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumental_procedures', to='examination_management.examinationplan', verbose_name='План обследования')),
            ],
            options={
                'verbose_name': 'Инструментальное исследование в плане',
                'verbose_name_plural': 'Инструментальные исследования в плане',
                'ordering': ['-created_at'],
            },
        ),
    ]
