# Generated by Django 5.2.4 on 2025-08-15 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_management', '0001_initial'),
        ('instrumental_procedures', '0002_initial'),
        ('lab_tests', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationinstrumental',
            name='procedure_definition',
        ),
        migrations.RemoveField(
            model_name='examinationlabtest',
            name='lab_test_assignment',
        ),
        migrations.AddField(
            model_name='examinationinstrumental',
            name='instrumental_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examination_instrumentals', to='instrumental_procedures.instrumentalproceduredefinition', verbose_name='Инструментальное исследование'),
        ),
        migrations.AddField(
            model_name='examinationlabtest',
            name='lab_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examination_lab_tests', to='lab_tests.labtestdefinition', verbose_name='Лабораторное исследование'),
        ),
    ]
