# Generated by Django 5.2.4 on 2025-09-04 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_management', '0003_remove_examinationinstrumental_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationplan',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='examinationplan',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='examinationplan',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='examinationplan',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='examinationplan',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='examinationplan',
            name='completion_notes',
        ),
        migrations.RemoveField(
            model_name='examinationplan',
            name='pause_reason',
        ),
        migrations.RemoveField(
            model_name='examinationplan',
            name='paused_at',
        ),
        migrations.RemoveField(
            model_name='examinationplan',
            name='paused_by',
        ),
        migrations.RemoveField(
            model_name='examinationplan',
            name='status',
        ),
        migrations.AddField(
            model_name='examinationplan',
            name='archive_reason',
            field=models.TextField(blank=True, verbose_name='Причина архивирования'),
        ),
        migrations.AddField(
            model_name='examinationplan',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования'),
        ),
        migrations.AddField(
            model_name='examinationplan',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировано пользователем'),
        ),
        migrations.AddField(
            model_name='examinationplan',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивировано'),
        ),
    ]
