# Generated by Django 5.2.4 on 2025-08-17 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('encounters', '0010_remove_treatment_models'),
        ('examination_management', '0003_alter_examinationinstrumental_instrumental_procedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationplan',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='examinationplan',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examinationplan',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examination_plans', to='encounters.encounter', verbose_name='Случай обращения'),
        ),
    ]
