# Generated by Django 5.2.4 on 2025-09-04 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_management', '0004_remove_examinationplan_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationinstrumental',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='examinationinstrumental',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отменено'),
        ),
        migrations.AddField(
            model_name='examinationinstrumental',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_instrumentals', to=settings.AUTH_USER_MODEL, verbose_name='Отменено пользователем'),
        ),
        migrations.AddField(
            model_name='examinationinstrumental',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('cancelled', 'Отменено'), ('completed', 'Завершено'), ('paused', 'Приостановлено')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='examinationlabtest',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='examinationlabtest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отменено'),
        ),
        migrations.AddField(
            model_name='examinationlabtest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_lab_tests', to=settings.AUTH_USER_MODEL, verbose_name='Отменено пользователем'),
        ),
        migrations.AddField(
            model_name='examinationlabtest',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('cancelled', 'Отменено'), ('completed', 'Завершено'), ('paused', 'Приостановлено')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
