# Generated by Django 5.2.4 on 2025-08-18 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('departments', '0002_initial'),
        ('encounters', '0010_remove_treatment_models'),
        ('examination_management', '0004_examinationplan_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель плана'),
        ),
        migrations.AddField(
            model_name='examinationplan',
            name='patient_department_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examination_plans', to='departments.patientdepartmentstatus', verbose_name='Статус пациента в отделении'),
        ),
        migrations.AddIndex(
            model_name='examinationplan',
            index=models.Index(fields=['patient_department_status', 'created_at'], name='examination_patient_ac461d_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationplan',
            index=models.Index(fields=['encounter', 'created_at'], name='examination_encount_289891_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationplan',
            index=models.Index(fields=['content_type', 'object_id', 'created_at'], name='examination_content_0d3ce8_idx'),
        ),
    ]
