# Generated by Django 5.2.4 on 2025-08-21 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_management', '0005_examinationplan_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationinstrumental',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='examinationlabtest',
            name='is_active',
        ),
        migrations.AddField(
            model_name='examinationinstrumental',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Укажите причину отмены назначения', verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='examinationinstrumental',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AddField(
            model_name='examinationinstrumental',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='Отменил'),
        ),
        migrations.AddField(
            model_name='examinationinstrumental',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='examinationinstrumental',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_completed', to=settings.AUTH_USER_MODEL, verbose_name='Завершил'),
        ),
        migrations.AddField(
            model_name='examinationinstrumental',
            name='completion_notes',
            field=models.TextField(blank=True, verbose_name='Примечания к завершению'),
        ),
        migrations.AddField(
            model_name='examinationinstrumental',
            name='pause_reason',
            field=models.TextField(blank=True, help_text='Укажите причину приостановки назначения', verbose_name='Причина приостановки'),
        ),
        migrations.AddField(
            model_name='examinationinstrumental',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата приостановки'),
        ),
        migrations.AddField(
            model_name='examinationinstrumental',
            name='paused_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_paused', to=settings.AUTH_USER_MODEL, verbose_name='Приостановил'),
        ),
        migrations.AddField(
            model_name='examinationinstrumental',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('paused', 'Приостановлено'), ('rejected', 'Забраковано')], db_index=True, default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='examinationlabtest',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Укажите причину отмены назначения', verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='examinationlabtest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AddField(
            model_name='examinationlabtest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='Отменил'),
        ),
        migrations.AddField(
            model_name='examinationlabtest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='examinationlabtest',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_completed', to=settings.AUTH_USER_MODEL, verbose_name='Завершил'),
        ),
        migrations.AddField(
            model_name='examinationlabtest',
            name='completion_notes',
            field=models.TextField(blank=True, verbose_name='Примечания к завершению'),
        ),
        migrations.AddField(
            model_name='examinationlabtest',
            name='pause_reason',
            field=models.TextField(blank=True, help_text='Укажите причину приостановки назначения', verbose_name='Причина приостановки'),
        ),
        migrations.AddField(
            model_name='examinationlabtest',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата приостановки'),
        ),
        migrations.AddField(
            model_name='examinationlabtest',
            name='paused_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_paused', to=settings.AUTH_USER_MODEL, verbose_name='Приостановил'),
        ),
        migrations.AddField(
            model_name='examinationlabtest',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('paused', 'Приостановлено'), ('rejected', 'Забраковано')], db_index=True, default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
