# Generated by Django 5.2.4 on 2025-09-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_management', '0005_examinationinstrumental_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationlabtest',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Время выполнения исследования', null=True, verbose_name='Время выполнения'),
        ),
    ]
