# Generated by Django 5.2.4 on 2025-09-04 18:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_management', '0006_examinationlabtest_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationlabtest',
            name='unique_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор назначения', verbose_name='Уникальный идентификатор'),
        ),
    ]
