# Generated by Django 5.2.4 on 2025-09-04 18:12

import uuid
from django.db import migrations


def generate_uuids(apps, schema_editor):
    """Генерирует UUID для существующих записей ExaminationLabTest"""
    ExaminationLabTest = apps.get_model('examination_management', 'ExaminationLabTest')
    for lab_test in ExaminationLabTest.objects.all():
        lab_test.unique_identifier = uuid.uuid4()
        lab_test.save(update_fields=['unique_identifier'])


class Migration(migrations.Migration):

    dependencies = [
        ('examination_management', '0007_examinationlabtest_unique_identifier'),
    ]

    operations = [
        migrations.RunPython(generate_uuids, reverse_code=migrations.RunPython.noop),
    ]
