# Generated by Django 5.2.4 on 2025-09-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_management', '0008_auto_20250904_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationlabtest',
            name='unique_identifier',
            field=models.UUIDField(help_text='Уникальный идентификатор назначения', unique=True, verbose_name='Уникальный идентификатор'),
        ),
    ]
