# Generated by Django 5.2.4 on 2025-09-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination_management', '0009_auto_20250904_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationlabtest',
            name='unique_identifier',
        ),
    ]
