# Generated by Django 5.2.4 on 2025-09-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_management', '0010_remove_unique_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationinstrumental',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Время выполнения исследования', null=True, verbose_name='Время выполнения'),
        ),
    ]
