# Generated by Django 5.2.4 on 2025-08-23 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('workflow_type', models.CharField(choices=[('simple', 'Простая подпись (только врач)'), ('standard', 'Стандартная (врач + заведующий)'), ('complex', 'Сложная (врач + заведующий + главный врач)'), ('critical', 'Критическая (врач + заведующий + главный врач + пациент)')], max_length=20, verbose_name='Тип процесса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('require_doctor_signature', models.BooleanField(default=True, verbose_name='Требуется подпись врача')),
                ('require_head_signature', models.BooleanField(default=False, verbose_name='Требуется подпись заведующего')),
                ('require_chief_signature', models.BooleanField(default=False, verbose_name='Требуется подпись главного врача')),
                ('require_patient_signature', models.BooleanField(default=False, verbose_name='Требуется подпись пациента')),
                ('auto_complete_on_doctor_signature', models.BooleanField(default=False, verbose_name='Автозавершение при подписи врача')),
                ('auto_complete_on_all_signatures', models.BooleanField(default=True, verbose_name='Автозавершение при всех подписях')),
                ('doctor_signature_timeout_days', models.PositiveIntegerField(default=7, verbose_name='Таймаут подписи врача (дни)')),
                ('head_signature_timeout_days', models.PositiveIntegerField(default=3, verbose_name='Таймаут подписи заведующего (дни)')),
                ('chief_signature_timeout_days', models.PositiveIntegerField(default=2, verbose_name='Таймаут подписи главного врача (дни)')),
                ('patient_signature_timeout_days', models.PositiveIntegerField(default=5, verbose_name='Таймаут подписи пациента (дни)')),
                ('allow_parallel_signatures', models.BooleanField(default=False, verbose_name='Разрешить параллельные подписи')),
                ('require_sequential_order', models.BooleanField(default=True, verbose_name='Требовать последовательный порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Рабочий процесс подписей',
                'verbose_name_plural': 'Рабочие процессы подписей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SignatureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('auto_apply', models.BooleanField(default=False, verbose_name='Автоматически применять')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('content_types', models.ManyToManyField(help_text='К каким типам документов применяется этот шаблон', to='contenttypes.contenttype', verbose_name='Типы документов')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_signatures.signatureworkflow', verbose_name='Рабочий процесс')),
            ],
            options={
                'verbose_name': 'Шаблон подписи',
                'verbose_name_plural': 'Шаблоны подписей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('signature_type', models.CharField(choices=[('doctor', 'Врач-исследователь'), ('head_of_department', 'Заведующий отделением'), ('chief_physician', 'Главный врач'), ('patient', 'Пациент'), ('nurse', 'Медсестра'), ('technician', 'Техник'), ('consultant', 'Консультант')], max_length=20, verbose_name='Тип подписи')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подписи'), ('signed', 'Подписано'), ('rejected', 'Отклонено'), ('expired', 'Истекло'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('signature_notes', models.TextField(blank=True, verbose_name='Комментарии к подписи')),
                ('signature_hash', models.CharField(blank=True, max_length=128, verbose_name='Хеш подписи')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарии')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('required_by', models.DateTimeField(blank=True, null=True, verbose_name='Требуется к')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подписано в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('actual_signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Фактический подписант')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('required_signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Требуемый подписант')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='document_signatures.signatureworkflow', verbose_name='Рабочий процесс')),
            ],
            options={
                'verbose_name': 'Подпись документа',
                'verbose_name_plural': 'Подписи документов',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='document_si_content_833a79_idx'), models.Index(fields=['status'], name='document_si_status_26182d_idx'), models.Index(fields=['required_signer'], name='document_si_require_c1508f_idx'), models.Index(fields=['workflow'], name='document_si_workflo_bd76a5_idx')],
                'unique_together': {('content_type', 'object_id', 'signature_type')},
            },
        ),
    ]
