# Generated by Django 5.2.4 on 2025-09-02 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archivable', models.BooleanField(default=True, verbose_name='Поддерживает архивирование')),
                ('cascade_archive', models.BooleanField(default=True, verbose_name='Каскадное архивирование')),
                ('cascade_restore', models.BooleanField(default=True, verbose_name='Каскадное восстановление')),
                ('auto_archive_related', models.BooleanField(default=True, verbose_name='Автоархивирование связанных')),
                ('archive_after_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Автоархивирование через дней')),
                ('show_archived_in_list', models.BooleanField(default=True, verbose_name='Показывать в списке')),
                ('show_archived_in_search', models.BooleanField(default=False, verbose_name='Показывать в поиске')),
                ('allow_restore', models.BooleanField(default=True, verbose_name='Разрешить восстановление')),
                ('require_reason', models.BooleanField(default=True, verbose_name='Требовать причину')),
                ('archive_permission', models.CharField(blank=True, max_length=100, verbose_name='Разрешение на архивирование')),
                ('restore_permission', models.CharField(blank=True, max_length=100, verbose_name='Разрешение на восстановление')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', unique=True)),
            ],
            options={
                'verbose_name': 'Конфигурация архивирования',
                'verbose_name_plural': 'Конфигурации архивирования',
                'ordering': ['content_type__app_label', 'content_type__model'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('archive', 'Архивирование'), ('restore', 'Восстановление'), ('delete', 'Удаление')], max_length=20, verbose_name='Действие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('previous_data', models.JSONField(blank=True, null=True, verbose_name='Предыдущие данные')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='Новые данные')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог архивирования',
                'verbose_name_plural': 'Логи архивирования',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='base_archiv_content_bee925_idx'), models.Index(fields=['action'], name='base_archiv_action_e05b1e_idx'), models.Index(fields=['timestamp'], name='base_archiv_timesta_f46987_idx'), models.Index(fields=['user'], name='base_archiv_user_id_901fc7_idx')],
            },
        ),
    ]
