# Generated by Django 5.2.3 on 2025-07-06 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Международное непатентованное наименование', max_length=255, unique=True, verbose_name='Название препарата (МНН)')),
                ('form', models.CharField(blank=True, help_text="Например, 'таблетки', 'раствор для инъекций'", max_length=100, null=True, verbose_name='Форма выпуска')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препараты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DosingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Краткое описание для кого это правило, н-р: 'Дети до 12 лет <40кг'", max_length=255, verbose_name='Название правила')),
                ('route_of_administration', models.CharField(blank=True, choices=[('oral', 'Внутрь'), ('iv', 'Внутривенно'), ('im', 'Внутримышечно'), ('subcutaneous', 'Подкожно'), ('other', 'Другое')], max_length=20, null=True, verbose_name='Путь введения')),
                ('min_age_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальный возраст (дней)')),
                ('max_age_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальный возраст (дней)')),
                ('min_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Минимальный вес (кг)')),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Максимальный вес (кг)')),
                ('is_loading_dose', models.BooleanField(default=False, verbose_name='Это начальная (нагрузочная) доза?')),
                ('dosage_value', models.DecimalField(blank=True, decimal_places=3, help_text='Например, 10 или 500', max_digits=10, null=True, verbose_name='Значение дозы')),
                ('dosage_unit', models.CharField(blank=True, help_text="Например, 'мг/кг/сутки' или 'мг'", max_length=50, null=True, verbose_name='Единица дозы')),
                ('frequency_text', models.CharField(blank=True, help_text="Например, 'каждые 12-24 часа' или '2-3 раза в сутки'", max_length=100, null=True, verbose_name='Текст частоты')),
                ('max_daily_dosage_text', models.CharField(blank=True, help_text="Например, 'не более 4 г/сутки'", max_length=100, null=True, verbose_name='Максимальная суточная доза (текст)')),
                ('notes', models.TextField(blank=True, help_text="Например, '3-дневный курс', 'вводить в течение 1-2 часов'", null=True, verbose_name='Примечания')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosing_rules', to='pharmacy.medication', verbose_name='Препарат')),
            ],
            options={
                'verbose_name': 'Правило дозирования',
                'verbose_name_plural': 'Правила дозирования',
                'ordering': ['medication', 'min_age_days'],
            },
        ),
    ]
