# Generated by Django 5.2.3 on 2025-07-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название препарата')),
                ('default_dosage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дозировка по умолчанию')),
                ('default_frequency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Частота по умолчанию')),
                ('default_duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Длительность по умолчанию')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения')),
                ('form', models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма выпуска')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('default_dosage_per_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Дозировка на кг по умолчанию')),
                ('default_dosage_per_kg_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица дозировки на кг')),
                ('default_frequency_hours_options', models.CharField(blank=True, help_text='Через запятую, например: 12,24', max_length=255, null=True, verbose_name='Варианты частоты (часы)')),
                ('default_route', models.CharField(blank=True, max_length=100, null=True, verbose_name='Путь введения по умолчанию')),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препараты',
                'ordering': ['name'],
            },
        ),
    ]
