# Generated by Django 5.2.4 on 2025-07-30 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
        ('pharmacy', '0001_initial'),
        ('treatment_assignments', '0002_remove_medicationassignment_dosing_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название способа введения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание способа введения')),
            ],
            options={
                'verbose_name': 'Способ введения',
                'verbose_name_plural': 'Способы введения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание группы')),
            ],
            options={
                'verbose_name': 'Группа препаратов',
                'verbose_name_plural': 'Группы препаратов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название формы выпуска')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание формы выпуска')),
            ],
            options={
                'verbose_name': 'Форма выпуска',
                'verbose_name_plural': 'Формы выпуска',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='medication',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='form',
        ),
        migrations.AddField(
            model_name='medication',
            name='external_info_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на полную информацию о препарате'),
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Напр., 'Стандартная терапия для взрослых' или 'Терапия неосложненной гонореи'", max_length=255, verbose_name='Название схемы')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Общие примечания к схеме')),
                ('indications', models.ManyToManyField(help_text='Диагнозы, при которых применяется эта схема', related_name='regimens', to='diagnosis.diagnosis', verbose_name='Показания (Диагнозы)')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regimens', to='pharmacy.medication', verbose_name='Препарат (МНН)')),
            ],
            options={
                'verbose_name': 'Схема применения',
                'verbose_name_plural': 'Схемы применения',
                'ordering': ['medication', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PopulationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основная группа', help_text="Напр., 'Взрослые и дети > 12 лет', 'Дети 6-12 лет'", max_length=255, verbose_name='Название группы пациентов')),
                ('min_age_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальный возраст (дней)')),
                ('max_age_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальный возраст (дней)')),
                ('min_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Минимальный вес (кг)')),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Максимальный вес (кг)')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population_criteria', to='pharmacy.regimen', verbose_name='Схема применения')),
            ],
            options={
                'verbose_name': 'Критерии пациента',
                'verbose_name_plural': 'Критерии пациентов',
            },
        ),
        migrations.CreateModel(
            name='DosingInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_type', models.CharField(choices=[('MAINTENANCE', 'Поддерживающая'), ('LOADING', 'Нагрузочная'), ('SINGLE', 'Однократная')], default='MAINTENANCE', max_length=20, verbose_name='Тип дозы')),
                ('dose_description', models.CharField(help_text="Напр., '400 мг' или '8 мг/кг массы тела'", max_length=255, verbose_name='Описание дозы')),
                ('frequency_description', models.CharField(help_text="Напр., '1 раз/сутки' или 'по 200 мг каждые 12 ч'", max_length=255, verbose_name='Описание частоты')),
                ('duration_description', models.CharField(help_text="Напр., '7-10 дней' или 'не менее 10 дней'", max_length=255, verbose_name='Описание длительности')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.administrationmethod', verbose_name='Путь введения')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosing_instructions', to='pharmacy.regimen', verbose_name='Схема применения')),
            ],
            options={
                'verbose_name': 'Инструкция по дозированию',
                'verbose_name_plural': 'Инструкции по дозированию',
            },
        ),
        migrations.CreateModel(
            name='RegimenAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(help_text="Напр., 'При КК от 21 до 60 мл/мин' или 'Пациенты на гемодиализе'", max_length=255, verbose_name='Условие для корректировки')),
                ('adjustment_description', models.CharField(help_text="Напр., 'суточную дозу следует уменьшить на 25%'", max_length=255, verbose_name='Описание корректировки')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='pharmacy.regimen', verbose_name='Схема применения')),
            ],
            options={
                'verbose_name': 'Корректировка схемы',
                'verbose_name_plural': 'Корректировки схем',
            },
        ),
        migrations.CreateModel(
            name='TradeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Торговое название')),
                ('external_info_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на полную информацию о препарате')),
                ('atc_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='АТХ код')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_names', to='pharmacy.medication', verbose_name='Активное вещество (МНН)')),
                ('medication_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='pharmacy.medicationgroup', verbose_name='Фармакологическая группа')),
                ('release_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='pharmacy.releaseform', verbose_name='Лекарственная форма')),
            ],
            options={
                'verbose_name': 'Торговое наименование',
                'verbose_name_plural': 'Торговые наименования',
            },
        ),
        migrations.DeleteModel(
            name='DosingRule',
        ),
    ]
