# Generated by Django 5.2.4 on 2025-08-06 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_administrationmethod_medicationgroup_releaseform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код препарата'),
        ),
        migrations.AddField(
            model_name='medication',
            name='code_system',
            field=models.CharField(blank=True, choices=[('atc', 'АТХ (Анатомо-терапевтическо-химическая классификация)'), ('rxnorm', 'RxNorm'), ('snomed', 'SNOMED CT'), ('icd10', 'МКБ-10'), ('who', 'ВОЗ'), ('local', 'Локальная система')], max_length=50, verbose_name='Система кодирования'),
        ),
        migrations.AddField(
            model_name='medication',
            name='generic_concept',
            field=models.ForeignKey(blank=True, help_text='Если это торговый препарат, укажите его действующее вещество (МНН) из этой же таблицы.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medication', verbose_name='Основа (МНН)'),
        ),
        migrations.AddField(
            model_name='medication',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='medication',
            name='medication_form',
            field=models.CharField(blank=True, choices=[('tablet', 'Таблетки'), ('capsule', 'Капсулы'), ('solution', 'Раствор'), ('ointment', 'Мазь'), ('suppository', 'Суппозитории'), ('gel', 'Гель'), ('cream', 'Крем'), ('syrup', 'Сироп'), ('suspension', 'Суспензия'), ('powder', 'Порошок'), ('injection', 'Инъекции'), ('drops', 'Капли'), ('spray', 'Спрей'), ('patch', 'Пластырь'), ('inhaler', 'Ингалятор')], max_length=100, verbose_name='Лекарственная форма'),
        ),
        migrations.AddField(
            model_name='medication',
            name='trade_name',
            field=models.CharField(blank=True, help_text='Торговое название препарата (если отличается от МНН)', max_length=255, null=True, verbose_name='Торговое название'),
        ),

    ]
