# Generated by Django 5.2.4 on 2025-08-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_medication_code_medication_code_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='code_system',
            field=models.CharField(choices=[('atc', 'АТХ (Анатомо-терапевтическо-химическая классификация)'), ('rxnorm', 'RxNorm'), ('snomed', 'SNOMED CT'), ('icd10', 'МКБ-10'), ('who', 'ВОЗ'), ('local', 'Локальная система')], default='atc', max_length=50, verbose_name='Система кодирования'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
