# Generated by Django 5.2.4 on 2025-08-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_medication_code_system_alter_medication_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradename',
            name='description',
            field=models.TextField(blank=True, help_text='Детальное описание формы выпуска, дозировки и упаковки', null=True, verbose_name='Описание формы выпуска'),
        ),
    ]
