# Generated by Django 5.2.4 on 2025-08-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_tradename_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradename',
            options={'verbose_name': 'Торговое название', 'verbose_name_plural': 'Торговые названия'},
        ),
        migrations.AlterUniqueTogether(
            name='tradename',
            unique_together={('name', 'medication')},
        ),
        migrations.AddField(
            model_name='tradename',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-12 10:53:00.123456+00:00', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradename',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='tradename',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='tradename',
            name='atc_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ATC код'),
        ),
        migrations.AlterField(
            model_name='tradename',
            name='external_info_url',
            field=models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='tradename',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medication', verbose_name='МНН'),
        ),
        migrations.AlterField(
            model_name='tradename',
            name='medication_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicationgroup', verbose_name='Группа препаратов'),
        ),
        migrations.AlterField(
            model_name='tradename',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tradename',
            name='release_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.releaseform', verbose_name='Форма выпуска'),
        ),
        migrations.RemoveField(
            model_name='tradename',
            name='description',
        ),
    ]
