# Generated by Django 5.2.4 on 2025-08-12 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_tradename_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradename',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_names', to='pharmacy.medication', verbose_name='МНН'),
        ),
    ]
