# Generated by Django 5.2.4 on 2025-08-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_alter_tradename_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosinginstruction',
            name='compatible_forms',
            field=models.ManyToManyField(blank=True, help_text='Формы выпуска, для которых подходит эта инструкция по дозированию', to='pharmacy.releaseform', verbose_name='Совместимые формы выпуска'),
        ),
    ]
