# Generated by Django 5.2.3 on 2025-07-06 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewbornProfile',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='_newborn_profile', serialize=False, to='patients.patient', verbose_name='Пациент')),
                ('birth_datetime', models.DateTimeField(null=True, verbose_name='Дата и время рождения')),
                ('gestational_age_weeks', models.PositiveIntegerField(verbose_name='Срок гестации (недель)')),
                ('birth_weight_grams', models.PositiveIntegerField(verbose_name='Вес при рождении (грамм)')),
                ('birth_height_cm', models.PositiveIntegerField(verbose_name='Рост при рождении (см)')),
                ('head_circumference_cm', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Окружность головы (см)')),
                ('apgar_score_1_min', models.PositiveIntegerField(verbose_name='Оценка по Апгар на 1-й минуте')),
                ('apgar_score_5_min', models.PositiveIntegerField(verbose_name='Оценка по Апгар на 5-й минуте')),
                ('notes', models.TextField(blank=True, verbose_name='Особенности течения родов и раннего периода')),
            ],
            options={
                'verbose_name': 'Профиль новорожденного',
                'verbose_name_plural': 'Профили новорожденных',
            },
        ),
    ]
