# Generated by Django 5.2.4 on 2025-07-13 16:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewbornProfile',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='_newborn_profile', serialize=False, to='patients.patient', verbose_name='Пациент')),
                ('birth_time', models.TimeField(null=True, verbose_name='Время рождения')),
                ('gestational_age_weeks', models.PositiveIntegerField(help_text='Срок гестации, недель', validators=[django.core.validators.MinValueValidator(22, message='Срок гестации должен быть не менее 22 недель'), django.core.validators.MaxValueValidator(44, message='Срок гестации должен быть не более 42 недель')], verbose_name='Срок гестации (недель)')),
                ('gestational_age_days', models.PositiveIntegerField(help_text='Срок гестации, дней', validators=[django.core.validators.MinValueValidator(0, message='Срок гестации должен быть не менее 0 дней'), django.core.validators.MaxValueValidator(7, message='Срок гестации должен быть не более 7 дней')], verbose_name='Срок гестации (дней)')),
                ('birth_weight_grams', models.PositiveIntegerField(verbose_name='Вес при рождении (грамм)')),
                ('birth_height_cm', models.PositiveIntegerField(verbose_name='Рост при рождении (см)')),
                ('head_circumference_cm', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Окружность головы (см)')),
                ('physical_development', models.TextField(blank=True, verbose_name='Физическое развитие')),
                ('apgar_score_1_min', models.PositiveIntegerField(null=True, verbose_name='Оценка по Апгар на 1-й минуте')),
                ('apgar_score_5_min', models.PositiveIntegerField(null=True, verbose_name='Оценка по Апгар на 5-й минуте')),
                ('apgar_score_10_min', models.PositiveIntegerField(null=True, verbose_name='Оценка по Апгар на 10-й минуте')),
                ('notes', models.TextField(blank=True, verbose_name='Особенности течения беременности и родов')),
                ('obstetric_history', models.TextField(blank=True, verbose_name='Акушерский диагноз')),
            ],
            options={
                'verbose_name': 'Профиль новорожденного',
                'verbose_name_plural': 'Профили новорожденных',
            },
        ),
    ]
