# Generated by Django 5.2.4 on 2025-07-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newborns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newbornprofile',
            name='birth_datetime',
        ),
        migrations.AddField(
            model_name='newbornprofile',
            name='birth_time',
            field=models.TimeField(null=True, verbose_name='Время рождения'),
        ),
    ]
