# Generated by Django 5.2.3 on 2025-07-05 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newborns', '0001_initial'),
        ('patients', '0002_patient_patient_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newbornprofile',
            name='birth_datetime',
        ),
        migrations.AlterField(
            model_name='newbornprofile',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newborns', to='patients.patient', verbose_name='Родитель'),
        ),
    ]
