# Generated by Django 5.2.4 on 2025-07-11 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newborns', '0002_remove_newbornprofile_birth_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbornprofile',
            name='apgar_score_10_min',
            field=models.PositiveIntegerField(null=True, verbose_name='Оценка по Апгар на 10-й минуте'),
        ),
        migrations.AddField(
            model_name='newbornprofile',
            name='gestational_age_days',
            field=models.PositiveIntegerField(default=5, help_text='Срок гестации, дней', validators=[django.core.validators.MinValueValidator(0, message='Срок гестации должен быть не менее 0 дней'), django.core.validators.MaxValueValidator(7, message='Срок гестации должен быть не более 7 дней')], verbose_name='Срок гестации (дней)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newbornprofile',
            name='obstetric_history',
            field=models.TextField(blank=True, verbose_name='Акушерский диагноз'),
        ),
        migrations.AddField(
            model_name='newbornprofile',
            name='physical_development',
            field=models.TextField(blank=True, verbose_name='Физическое развитие'),
        ),
        migrations.AlterField(
            model_name='newbornprofile',
            name='apgar_score_1_min',
            field=models.PositiveIntegerField(null=True, verbose_name='Оценка по Апгар на 1-й минуте'),
        ),
        migrations.AlterField(
            model_name='newbornprofile',
            name='apgar_score_5_min',
            field=models.PositiveIntegerField(null=True, verbose_name='Оценка по Апгар на 5-й минуте'),
        ),
        migrations.AlterField(
            model_name='newbornprofile',
            name='gestational_age_weeks',
            field=models.PositiveIntegerField(help_text='Срок гестации, недель', validators=[django.core.validators.MinValueValidator(22, message='Срок гестации должен быть не менее 22 недель'), django.core.validators.MaxValueValidator(44, message='Срок гестации должен быть не более 42 недель')], verbose_name='Срок гестации (недель)'),
        ),
        migrations.AlterField(
            model_name='newbornprofile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Особенности течения беременности и родов'),
        ),
    ]
