# Generated by Django 5.2.3 on 2025-07-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newborns', '0002_remove_newbornprofile_birth_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newbornprofile',
            name='mother',
        ),
    ]
