# Generated by Django 5.2.3 on 2025-07-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newborns', '0003_remove_newbornprofile_mother'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbornprofile',
            name='birth_datetime',
            field=models.DateTimeField(null=True, verbose_name='Дата и время рождения'),
        ),
    ]
