# Generated by Django 5.2.3 on 2025-07-03 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('general_treatments', '0001_initial'),
        ('instrumental_procedures', '0001_initial'),
        ('lab_tests', '0001_initial'),
        ('patients', '0001_initial'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTreatmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('paused', 'Приостановлено')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigning_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Назначивший врач')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('general_treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_assignments', to='general_treatments.generaltreatmentdefinition', verbose_name='Общее назначение')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Общее назначение',
                'verbose_name_plural': 'Общие назначения',
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentalProcedureAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('paused', 'Приостановлено')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigning_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Назначивший врач')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('instrumental_procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumental_assignments', to='instrumental_procedures.instrumentalproceduredefinition', verbose_name='Инструментальное исследование')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Назначение инструментального исследования',
                'verbose_name_plural': 'Назначения инструментальных исследований',
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabTestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('paused', 'Приостановлено')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigning_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Назначивший врач')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_assignments', to='lab_tests.labtestdefinition', verbose_name='Лабораторное исследование')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Назначение лабораторного исследования',
                'verbose_name_plural': 'Назначения лабораторных исследований',
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('paused', 'Приостановлено')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес пациента (кг)')),
                ('dosage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дозировка')),
                ('frequency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Частота')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Длительность')),
                ('route', models.CharField(blank=True, max_length=100, null=True, verbose_name='Путь введения')),
                ('assigning_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Назначивший врач')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medication_assignments', to='pharmacy.medication', verbose_name='Препарат')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Назначение препарата',
                'verbose_name_plural': 'Назначения препаратов',
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
    ]
