# Generated by Django 5.2.3 on 2025-07-03 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('patients', '0001_initial'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('assignment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время назначения')),
                ('dosage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дозировка')),
                ('frequency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Частота')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Длительность')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('paused', 'Приостановлено')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigning_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Назначивший врач')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='pharmacy.medication', verbose_name='Препарат')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_assignments', to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Назначение лечения',
                'verbose_name_plural': 'Назначения лечения',
                'ordering': ['-assignment_date'],
            },
        ),
    ]
