# Generated by Django 5.2.3 on 2025-07-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentassignment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='treatmentassignment',
            name='start_date',
            field=models.DateTimeField(default='2025-07-01 10:20:00', verbose_name='Дата начала'),
            preserve_default=False,
        ),
    ]
