# Generated by Django 5.2.3 on 2025-07-03 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('treatment_assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaltreatmentassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='generaltreatmentassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('paused', 'Приостановлено')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='generaltreatmentassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='instrumentalprocedureassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='instrumentalprocedureassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('paused', 'Приостановлено')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='instrumentalprocedureassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='labtestassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='labtestassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('paused', 'Приостановлено')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='labtestassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='medicationassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='medicationassignment',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='pharmacy.medication', verbose_name='Препарат'),
        ),
        migrations.AlterField(
            model_name='medicationassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('paused', 'Приостановлено')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='medicationassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
