# Generated by Django 5.2.4 on 2025-07-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationassignment',
            name='dosing_rule',
        ),
    ]
