# Generated by Django 5.2.4 on 2025-08-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_assignments', '0002_remove_medicationassignment_dosing_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaltreatmentassignment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина брака'),
        ),
        migrations.AddField(
            model_name='instrumentalprocedureassignment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина брака'),
        ),
        migrations.AddField(
            model_name='labtestassignment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина брака'),
        ),
        migrations.AddField(
            model_name='medicationassignment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина брака'),
        ),
        migrations.AlterField(
            model_name='generaltreatmentassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('paused', 'Приостановлено'), ('rejected', 'Забраковано')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='instrumentalprocedureassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('paused', 'Приостановлено'), ('rejected', 'Забраковано')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='labtestassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('paused', 'Приостановлено'), ('rejected', 'Забраковано')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='medicationassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('canceled', 'Отменено'), ('paused', 'Приостановлено'), ('rejected', 'Забраковано')], default='active', max_length=10, verbose_name='Статус'),
        ),
    ]
