# Generated by Django 5.2.3 on 2025-07-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_assignments', '0002_alter_generaltreatmentassignment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaltreatmentassignment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='instrumentalprocedureassignment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='labtestassignment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='medicationassignment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AlterField(
            model_name='generaltreatmentassignment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения'),
        ),
        migrations.AlterField(
            model_name='generaltreatmentassignment',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата и время назначения'),
        ),
        migrations.AlterField(
            model_name='instrumentalprocedureassignment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения'),
        ),
        migrations.AlterField(
            model_name='instrumentalprocedureassignment',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата и время назначения'),
        ),
        migrations.AlterField(
            model_name='labtestassignment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения'),
        ),
        migrations.AlterField(
            model_name='labtestassignment',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата и время назначения'),
        ),
        migrations.AlterField(
            model_name='medicationassignment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения'),
        ),
        migrations.AlterField(
            model_name='medicationassignment',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата и время назначения'),
        ),
    ]
