# Generated by Django 5.2.3 on 2025-07-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_assignments', '0004_alter_medicationassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationassignment',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите длительность курса в днях', null=True, verbose_name='Длительность (дней)'),
        ),
    ]
