# Generated by Django 5.2.3 on 2025-07-04 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_assignments', '0005_medicationassignment_duration_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generaltreatmentassignment',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_completed_treatments', to=settings.AUTH_USER_MODEL, verbose_name='Завершено кем'),
        ),
        migrations.AddField(
            model_name='instrumentalprocedureassignment',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumental_completed_treatments', to=settings.AUTH_USER_MODEL, verbose_name='Завершено кем'),
        ),
        migrations.AddField(
            model_name='labtestassignment',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_completed_treatments', to=settings.AUTH_USER_MODEL, verbose_name='Завершено кем'),
        ),
        migrations.AddField(
            model_name='medicationassignment',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_completed_treatments', to=settings.AUTH_USER_MODEL, verbose_name='Завершено кем'),
        ),
        migrations.AlterField(
            model_name='generaltreatmentassignment',
            name='assigning_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_assigned_treatments', to=settings.AUTH_USER_MODEL, verbose_name='Назначивший врач'),
        ),
        migrations.AlterField(
            model_name='instrumentalprocedureassignment',
            name='assigning_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumental_assigned_treatments', to=settings.AUTH_USER_MODEL, verbose_name='Назначивший врач'),
        ),
        migrations.AlterField(
            model_name='labtestassignment',
            name='assigning_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_assigned_treatments', to=settings.AUTH_USER_MODEL, verbose_name='Назначивший врач'),
        ),
        migrations.AlterField(
            model_name='medicationassignment',
            name='assigning_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_assigned_treatments', to=settings.AUTH_USER_MODEL, verbose_name='Назначивший врач'),
        ),
    ]
