"""
Django settings for base project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w#-a1_%qf)rfvr$tg@nv6+)&q9((tozdrv+h5k=is2uh7js!lj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'django_select2',
    'widget_tweaks',
    'recurrence',
    'rest_framework',
    'django_extensions',
    'crispy_forms',
    'crispy_bootstrap5',
]

LOCAL_APPS = [
    'base',  # Добавляем базовое приложение
    'authentication',
    'profiles',
    'patients',
    'appointments',
    'encounters',
    'documents',
    'departments',
    # 'treatment_assignments',  # УДАЛЕНО
    'treatment_management',
    'pharmacy',
    'lab_tests',
    'instrumental_procedures',
    'newborns',
    'diagnosis',
    'examination_management',
    'clinical_scheduling',
    'document_signatures',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'authentication.middleware.LoginBlockingMiddleware',  # Добавляем наш middleware
    'authentication.middleware.IPFilteringMiddleware',  # Добавляем IP-фильтр
]

ROOT_URLCONF = 'base.urls'

DEPARTMENT_SLUGS = {
    'admission': 'admission', # Техническое отделение для приёма пациентов (соответствует Encounter)
    'pediatrics': 'pediatrics',
    'neonatology': 'neonatology',
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'base.context_processors.department_slugs',
            ],
        },
    },
]

WSGI_APPLICATION = 'base.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Настройки для корректной работы с временными зонами
DATETIME_FORMAT = 'd.m.Y H:i'
DATE_FORMAT = 'd.m.Y'
TIME_FORMAT = 'H:i'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'patients', 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Select2 настройки
SELECT2_CACHE_BACKEND = "default"
SELECT2_CACHE_PREFIX = "select2"

# Настройки для Select2 виджетов
SELECT2_JS = 'https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js'
SELECT2_CSS = 'https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css'

# Настройки для django-select2
SELECT2_CACHE_BACKEND = "default"
SELECT2_CACHE_PREFIX = "select2"

# Crispy Forms
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Настройки аутентификации
LOGIN_URL = 'authentication:login'
LOGIN_REDIRECT_URL = 'patients:home'
LOGOUT_REDIRECT_URL = 'authentication:login'

# Настройки сессии
SESSION_COOKIE_AGE = 3600  # 1 час
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

# Настройки языка
LANGUAGE_CODE = 'ru-ru'

# Настройки кэша для ограничения попыток входа
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Настройки для ограничения попыток входа
LOGIN_ATTEMPTS_LIMIT = 3
LOGIN_ATTEMPTS_TIMEOUT = 300  # 5 минут блокировки

# IP-фильтрация для входа в систему
IP_WHITELIST_ENABLED = True  # Включить/выключить IP-фильтрацию
IP_BLOCKED_RESPONSE_TYPE = '403'  # Тип ответа для заблокированных IP: '403', '404', 'redirect'

# Разрешенные IP-адреса (точные)
ALLOWED_LOGIN_IPS = [
    '127.0.0.1',          # localhost (для разработки)
    '::1',                 # localhost IPv6
    # '192.168.1.100',    # Ваш рабочий компьютер (раскомментируйте и добавьте свой IP)
    # '10.0.0.50',        # Другой разрешенный IP
]

# Разрешенные сети/подсети
ALLOWED_LOGIN_NETWORKS = [
    # '127.0.0.0/8',        # localhost сеть
    # '192.168.1.0/24',   # Вся сеть 192.168.1.x (раскомментируйте для офиса)
    # '10.0.0.0/16',      # Сеть 10.0.x.x
]

# Дополнительные настройки безопасности
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Настройки для защиты от CSRF
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Настройки для защиты сессий
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'


