# Generated by Django 5.2.3 on 2025-06-29 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0003_alter_encounter_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('inspection', 'Осмотр'), ('daily_note', 'Дневник наблюдения'), ('consultation', 'Консультация специалиста'), ('discharge_summary', 'Выписка'), ('epicrisis', 'Эпикриз'), ('transfer_note', 'Переводной эпикриз')], max_length=30, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('is_signed', models.BooleanField(default=False, verbose_name='Подписан')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Аннулирован')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='encounters.encounter')),
            ],
            options={
                'verbose_name': 'Медицинский документ',
                'verbose_name_plural': 'Медицинские документы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/attachments/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.clinicaldocument')),
            ],
            options={
                'verbose_name': 'Вложение к документу',
                'verbose_name_plural': 'Вложения к документам',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('document_type', models.CharField(choices=[('inspection', 'Осмотр'), ('daily_note', 'Дневник наблюдения'), ('consultation', 'Консультация специалиста'), ('discharge_summary', 'Выписка'), ('epicrisis', 'Эпикриз'), ('transfer_note', 'Переводной эпикриз')], max_length=30, verbose_name='Тип документа')),
                ('default_content', models.TextField(verbose_name='Содержимое по умолчанию')),
                ('is_global', models.BooleanField(default=False, verbose_name='Общий шаблон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор шаблона')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['document_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttemplate'),
        ),
    ]
