# Generated by Django 5.2.3 on 2025-07-06 16:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('departments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа документа')),
                ('schema', models.JSONField(help_text='Описывает поля, их типы и метки', verbose_name='Схема полей документа (JSON)')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_types', to='departments.department', verbose_name='Отделение (опционально)')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('author_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность автора')),
                ('datetime_document', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('is_signed', models.BooleanField(default=False, verbose_name='Подписан')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Аннулирован')),
                ('data', models.JSONField(default=dict, verbose_name='Данные документа')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Клинический документ',
                'verbose_name_plural': 'Клинические документы',
                'ordering': ['-datetime_document'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('is_global', models.BooleanField(default=False, verbose_name='Общий шаблон')),
                ('template_data', models.JSONField(default=dict, verbose_name='Данные шаблона')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор шаблона')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='documents.documenttype')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'unique_together': {('name', 'document_type')},
            },
        ),
    ]
