# Generated by Django 5.2.4 on 2025-08-18 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('departments', '0002_initial'),
        ('documents', '0001_initial'),
        ('encounters', '0010_remove_treatment_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldocument',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_documents', to='encounters.encounter', verbose_name='Случай обращения'),
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='patient_department_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_documents', to='departments.patientdepartmentstatus', verbose_name='Статус пациента в отделении'),
        ),
        migrations.AlterField(
            model_name='clinicaldocument',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='clinicaldocument',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='clinicaldocument',
            index=models.Index(fields=['patient_department_status', 'created_at'], name='documents_c_patient_6c54cc_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocument',
            index=models.Index(fields=['encounter', 'created_at'], name='documents_c_encount_53c0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocument',
            index=models.Index(fields=['content_type', 'object_id', 'created_at'], name='documents_c_content_f87264_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicaldocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content_type__isnull', True), ('encounter__isnull', True), ('patient_department_status__isnull', False)), models.Q(('content_type__isnull', True), ('encounter__isnull', False), ('patient_department_status__isnull', True)), models.Q(('content_type__isnull', False), ('encounter__isnull', True), ('patient_department_status__isnull', True)), _connector='OR'), name='single_content_object_constraint'),
        ),
    ]
