# Generated by Django 5.2.3 on 2025-07-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldocument',
            name='author_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность автора'),
        ),
    ]
