# Generated by Django 5.2.3 on 2025-06-29 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicaldocument',
            name='encounter',
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
