# Generated by Django 5.2.4 on 2025-09-02 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_clinicaldocument_encounter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldocument',
            name='archive_reason',
            field=models.TextField(blank=True, verbose_name='Причина архивирования'),
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования'),
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировано пользователем'),
        ),
        migrations.AddField(
            model_name='clinicaldocument',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивировано'),
        ),
    ]
