# Generated by Django 5.2.4 on 2025-07-13 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название лабораторного исследования')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('schema', models.JSONField(blank=True, help_text='Описывает поля, их типы и метки', null=True, verbose_name='Схема полей результата (JSON)')),
            ],
            options={
                'verbose_name': 'Лабораторное исследование (определение)',
                'verbose_name_plural': 'Лабораторные исследования (определения)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_result', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата результата')),
                ('data', models.JSONField(default=dict, verbose_name='Данные результата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Результат лабораторного исследования',
                'verbose_name_plural': 'Результаты лабораторных исследований',
                'ordering': ['-datetime_result'],
            },
        ),
    ]
