# Generated by Django 5.2.3 on 2025-07-07 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_tests', '0001_initial'),
        ('treatment_assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestresult',
            name='lab_test_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='treatment_assignments.labtestassignment', verbose_name='Назначение лабораторного исследования'),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='procedure_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='lab_tests.labtestdefinition', verbose_name='Тип исследования'),
        ),
    ]
