# Generated by Django 5.2.4 on 2025-08-23 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_management', '0001_initial'),
        ('lab_tests', '0002_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestresult',
            name='examination_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_results', to='examination_management.examinationplan', verbose_name='План обследования'),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_results', to='patients.patient', verbose_name='Пациент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='procedure_definition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='lab_tests.labtestdefinition', verbose_name='Тип исследования'),
            preserve_default=False,
        ),
    ]
