# Generated by Django 5.2.4 on 2025-08-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0003_labtestresult_examination_plan_labtestresult_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestresult',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Заполнены ли данные результата', verbose_name='Заполнено'),
        ),
    ]
