# Generated by Django 5.2.4 on 2025-09-04 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0004_labtestresult_is_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestresult',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отменено'),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_lab_test_results', to=settings.AUTH_USER_MODEL, verbose_name='Отменено пользователем'),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('cancelled', 'Отменено'), ('completed', 'Завершено'), ('paused', 'Приостановлено')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
