# Generated by Django 5.2.3 on 2025-07-04 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Основная должность'),
        ),
        migrations.CreateModel(
            name='TemporaryPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255, verbose_name='Название временной должности')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_positions', to='profiles.doctorprofile')),
            ],
            options={
                'verbose_name': 'Временная должность',
                'verbose_name_plural': 'Временные должности',
                'ordering': ['start_date'],
            },
        ),
    ]
