# Generated by Django 5.2.4 on 2025-07-13 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(choices=[('adult', 'Взрослый'), ('newborn', 'Новорожденный'), ('child', 'Ребенок'), ('teen', 'Подросток')], default='adult', max_length=10, verbose_name='Тип пациента')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой'), ('unknown', 'Неизвестно')], max_length=10, verbose_name='Пол')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='patients.patient', verbose_name='Родители')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['last_name', 'first_name', 'birth_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_address', models.TextField(blank=True, verbose_name='Адрес регистрации')),
                ('residential_address', models.TextField(blank=True, verbose_name='Адрес проживания')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Адрес пациента',
                'verbose_name_plural': 'Адреса пациентов',
            },
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('legal_representative_full_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО представителя')),
                ('legal_representative_relation', models.CharField(blank=True, max_length=100, verbose_name='Родство / статус')),
                ('legal_representative_contacts', models.CharField(blank=True, max_length=100, verbose_name='Контакты представителя')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Контакт пациента',
                'verbose_name_plural': 'Контакты пациентов',
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, max_length=50, verbose_name='Тип документа')),
                ('passport_series', models.CharField(blank=True, max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=6, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(blank=True, max_length=255, verbose_name='Кем выдан')),
                ('passport_issued_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('passport_department_code', models.CharField(blank=True, max_length=7, verbose_name='Код подразделения')),
                ('snils', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='СНИЛС')),
                ('insurance_policy_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Полис ОМС/ДМС')),
                ('insurance_company', models.CharField(blank=True, max_length=100, verbose_name='Страховая компания')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Документ пациента',
                'verbose_name_plural': 'Документы пациентов',
            },
        ),
    ]
