# Generated by Django 5.2.3 on 2025-06-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('given', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой'), ('unknown', 'Неизвестно')], max_length=10, verbose_name='Пол')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address_text', models.TextField(blank=True, verbose_name='Адрес (строкой)')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='Почтовый индекс')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Страна')),
                ('snils', models.CharField(blank=True, max_length=14, verbose_name='СНИЛС')),
                ('insurance_policy', models.CharField(blank=True, max_length=30, verbose_name='Полис ОМС')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта')),
                ('deceased', models.BooleanField(default=False, verbose_name='Умер')),
                ('blood_type', models.CharField(blank=True, max_length=5, verbose_name='Группа крови')),
                ('allergies', models.TextField(blank=True, verbose_name='Аллергии')),
                ('chronic_conditions', models.TextField(blank=True, verbose_name='Хронические заболевания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['family', 'given'],
            },
        ),
    ]
