# Generated by Django 5.2.4 on 2025-09-02 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='archive_reason',
            field=models.TextField(blank=True, verbose_name='Причина архивирования'),
        ),
        migrations.AddField(
            model_name='patient',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования'),
        ),
        migrations.AddField(
            model_name='patient',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировано пользователем'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивировано'),
        ),
        migrations.AddField(
            model_name='patientcontact',
            name='archive_reason',
            field=models.TextField(blank=True, verbose_name='Причина архивирования'),
        ),
        migrations.AddField(
            model_name='patientcontact',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования'),
        ),
        migrations.AddField(
            model_name='patientcontact',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировано пользователем'),
        ),
        migrations.AddField(
            model_name='patientcontact',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивировано'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='patients_pa_last_na_1b32a7_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['birth_date'], name='patients_pa_birth_d_51eba5_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_archived'], name='patients_pa_is_arch_b8e241_idx'),
        ),
    ]
