# Generated by Django 5.2.3 on 2025-06-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='rhesus_factor',
            field=models.CharField(blank=True, choices=[('', '---------'), ('+', 'Положительный (+)'), ('-', 'Отрицательный (-)')], max_length=1, verbose_name='Резус-фактор'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('O(I)', 'O (I)'), ('A(II)', 'A (II)'), ('B(III)', 'B (III)'), ('AB(IV)', 'AB (IV)')], max_length=6, verbose_name='Группа крови'),
        ),
    ]
