# Generated by Django 5.2.3 on 2025-07-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('adult', 'Взрослый/Ребенок'), ('newborn', 'Новорожденный')], default='adult', max_length=10, verbose_name='Тип пациента'),
        ),
    ]
