# Generated by Django 5.2.3 on 2025-06-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_rhesus_factor_alter_patient_blood_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='deceased',
        ),
    ]
