# Generated by Django 5.2.3 on 2025-07-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_patient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='patients.patient', verbose_name='Родители'),
        ),
    ]
