# Generated by Django 5.2.3 on 2025-07-05 18:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_parents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name', 'birth_date'], 'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_company',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_policy_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='legal_representative_contacts',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='legal_representative_full_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='legal_representative_relation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='passport_department_code',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='passport_issued_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='passport_issued_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='passport_series',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='registration_address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='residential_address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='snils',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('adult', 'Взрослый'), ('newborn', 'Новорожденный'), ('child', 'Ребенок'), ('teen', 'Подросток')], default='adult', max_length=10, verbose_name='Тип пациента'),
        ),
        migrations.CreateModel(
            name='PatientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_address', models.TextField(blank=True, verbose_name='Адрес регистрации')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Адрес пациента',
                'verbose_name_plural': 'Адреса пациентов',
            },
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона.', regex='^\\+?[\\d\\s\\-]+$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Контакт пациента',
                'verbose_name_plural': 'Контакты пациентов',
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50, verbose_name='Тип документа')),
                ('document_number', models.CharField(max_length=50, verbose_name='Номер документа')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Документ пациента',
                'verbose_name_plural': 'Документы пациентов',
            },
        ),
    ]
