# Generated by Django 5.2.3 on 2025-06-28 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_deceased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='rhesus_factor',
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рост при рождении (см)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='Вес при рождении (кг)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='deceased',
            field=models.BooleanField(default=False, verbose_name='Умер'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gestation_weeks',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок гестации (нед.)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=50, verbose_name='Контакт представителя'),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО законного представителя'),
        ),
        migrations.AddField(
            model_name='patient',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='patients.patient', verbose_name='Родители'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
