# Generated by Django 5.2.3 on 2025-07-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_options_remove_patient_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdocument',
            name='document_number',
        ),
        migrations.AddField(
            model_name='patientaddress',
            name='residential_address',
            field=models.TextField(blank=True, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='patientcontact',
            name='legal_representative_contacts',
            field=models.CharField(blank=True, max_length=100, verbose_name='Контакты представителя'),
        ),
        migrations.AddField(
            model_name='patientcontact',
            name='legal_representative_full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО представителя'),
        ),
        migrations.AddField(
            model_name='patientcontact',
            name='legal_representative_relation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Родство / статус'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='insurance_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страховая компания'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Полис ОМС/ДМС'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='passport_department_code',
            field=models.CharField(blank=True, max_length=7, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='passport_issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='passport_number',
            field=models.CharField(blank=True, max_length=6, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='passport_series',
            field=models.CharField(blank=True, max_length=4, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='snils',
            field=models.CharField(blank=True, max_length=14, verbose_name='СНИЛС'),
        ),
    ]
