# Generated by Django 5.2.3 on 2025-07-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_patientdocument_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdocument',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип документа'),
        ),
    ]
