# Generated by Django 5.2.3 on 2025-06-28 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_rhesus_factor_alter_patient_blood_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='given',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='family',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='middle',
            new_name='middle_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address_text',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birth_height',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birth_weight',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='chronic_conditions',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='city',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='country',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='deceased',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gestation_weeks',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='guardian_contact',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_policy',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='rhesus_factor',
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страховая компания'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Полис ОМС/ДМС'),
        ),
        migrations.AddField(
            model_name='patient',
            name='legal_representative_contacts',
            field=models.CharField(blank=True, max_length=100, verbose_name='Контакты представителя'),
        ),
        migrations.AddField(
            model_name='patient',
            name='legal_representative_full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО представителя'),
        ),
        migrations.AddField(
            model_name='patient',
            name='legal_representative_relation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Родство / статус'),
        ),
        migrations.AddField(
            model_name='patient',
            name='passport_department_code',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}$', 'Формат: 000-000')], verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='patient',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='patient',
            name='passport_issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='patient',
            name='passport_series',
            field=models.CharField(blank=True, max_length=4, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_address',
            field=models.TextField(blank=True, verbose_name='Адрес регистрации'),
        ),
        migrations.AddField(
            model_name='patient',
            name='residential_address',
            field=models.TextField(blank=True, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='passport_number',
            field=models.CharField(blank=True, max_length=6, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
