# Generated by Django 5.2.3 on 2025-06-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='passport_department_code',
            field=models.CharField(blank=True, max_length=7, verbose_name='Код подразделения'),
        ),
    ]
