# Generated by Django 5.2.4 on 2025-08-20 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('scheduled_date', models.DateField(verbose_name='Запланированная дата')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='Запланированное время')),
                ('execution_status', models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Выполнено'), ('skipped', 'Пропущено'), ('partial', 'Введено не полностью'), ('canceled', 'Отменено'), ('rejected', 'Забраковано')], default='scheduled', max_length=20, verbose_name='Статус выполнения')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('execution_notes', models.TextField(blank=True, verbose_name='Примечания к выполнению')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина брака')),
                ('rejection_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата брака')),
                ('partial_reason', models.TextField(blank=True, verbose_name='Причина неполного выполнения')),
                ('partial_amount', models.CharField(blank=True, max_length=100, verbose_name='Выполненное количество')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Выполнил')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Забраковал')),
            ],
            options={
                'verbose_name': 'Запланированное клиническое событие',
                'verbose_name_plural': 'Запланированные клинические события',
                'ordering': ['scheduled_date', 'scheduled_time'],
                'indexes': [models.Index(fields=['scheduled_date', 'execution_status'], name='clinical_sc_schedul_4a45f0_idx'), models.Index(fields=['content_type', 'object_id'], name='clinical_sc_content_045572_idx'), models.Index(fields=['execution_status', 'scheduled_date'], name='clinical_sc_executi_d69b88_idx')],
                'unique_together': {('content_type', 'object_id', 'scheduled_date', 'scheduled_time')},
            },
        ),
    ]
