# Generated by Django 5.2.4 on 2025-08-21 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_scheduling', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('departments', '0002_initial'),
        ('encounters', '0010_remove_treatment_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledappointment',
            name='created_by_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Создатель назначения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledappointment',
            name='created_in_department',
            field=models.ForeignKey(default=1, help_text='Отделение, в котором было создано назначение', on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Отделение создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledappointment',
            name='created_in_encounter',
            field=models.ForeignKey(default=1, help_text='Случай поступления, в рамках которого создано назначение', on_delete=django.db.models.deletion.CASCADE, to='encounters.encounter', verbose_name='Случай поступления'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='scheduledappointment',
            index=models.Index(fields=['created_in_department', 'scheduled_date'], name='clinical_sc_created_491e60_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledappointment',
            index=models.Index(fields=['created_in_encounter', 'scheduled_date'], name='clinical_sc_created_138b2a_idx'),
        ),
    ]
