# Generated by Django 5.2.4 on 2025-08-21 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_scheduling', '0002_scheduledappointment_created_by_user_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('departments', '0002_initial'),
        ('encounters', '0010_remove_treatment_models'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scheduledappointment',
            name='clinical_sc_created_491e60_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduledappointment',
            name='clinical_sc_created_138b2a_idx',
        ),
        migrations.RemoveField(
            model_name='scheduledappointment',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='scheduledappointment',
            name='created_in_department',
        ),
        migrations.RemoveField(
            model_name='scheduledappointment',
            name='created_in_encounter',
        ),
        migrations.AddField(
            model_name='scheduledappointment',
            name='created_department',
            field=models.ForeignKey(default=1, help_text='Отделение, где было создано это назначение', on_delete=django.db.models.deletion.CASCADE, related_name='created_appointments', to='departments.department', verbose_name='Отделение создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledappointment',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_appointments', to='encounters.encounter', verbose_name='Случай поступления'),
        ),
        migrations.AddField(
            model_name='scheduledappointment',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_appointments', to='patients.patient', verbose_name='Пациент'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='scheduledappointment',
            index=models.Index(fields=['patient', 'scheduled_date'], name='clinical_sc_patient_86266a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledappointment',
            index=models.Index(fields=['created_department', 'scheduled_date'], name='clinical_sc_created_9f8876_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledappointment',
            index=models.Index(fields=['encounter', 'scheduled_date'], name='clinical_sc_encount_1aa9c2_idx'),
        ),
    ]
