# Generated by Django 5.2.4 on 2025-09-04 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_scheduling', '0003_remove_scheduledappointment_clinical_sc_created_491e60_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledappointment',
            options={'ordering': ['-scheduled_date', 'scheduled_time'], 'verbose_name': 'Запланированное клиническое событие', 'verbose_name_plural': 'Запланированные клинические события'},
        ),
        migrations.AddField(
            model_name='scheduledappointment',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Отменил'),
        ),
        migrations.AddField(
            model_name='scheduledappointment',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AddField(
            model_name='scheduledappointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
    ]
