# Generated by Django 5.2.4 on 2025-07-13 16:41

import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивировано')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации')),
                ('start', models.DateTimeField(verbose_name='Начало приема')),
                ('end', models.DateTimeField(verbose_name='Конец приема')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='scheduled', max_length=20)),
            ],
            options={
                'verbose_name': 'Запись на прием',
                'verbose_name_plural': 'Записи на прием',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала смены')),
                ('end_time', models.TimeField(verbose_name='Время окончания смены')),
                ('duration', models.PositiveSmallIntegerField(default=30, verbose_name='Длительность приема (мин)')),
                ('recurrences', recurrence.fields.RecurrenceField()),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
