# Generated by Django 5.2.4 on 2025-07-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmentevent_encounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentevent',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='appointmentevent',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивировано'),
        ),
    ]
