# Generated by Django 5.2.4 on 2025-09-02 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentevent',
            name='archive_reason',
            field=models.TextField(blank=True, verbose_name='Причина архивирования'),
        ),
        migrations.AddField(
            model_name='appointmentevent',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировано пользователем'),
        ),
        migrations.AlterField(
            model_name='appointmentevent',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования'),
        ),
    ]
