# Generated by Django 5.2.3 on 2025-07-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='appointment_duration',
            field=models.PositiveSmallIntegerField(default=30, help_text='Стандартная продолжительность одного приема в минутах.', verbose_name='Длительность приема (мин)'),
        ),
    ]
