# Generated by Django 5.2.4 on 2025-07-07 20:06

import django.db.models.deletion
import recurrence.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_schedule_appointment_duration'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='doctor',
        ),
        migrations.CreateModel(
            name='AppointmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Начало события')),
                ('end', models.DateTimeField(verbose_name='Конец события')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='scheduled', max_length=20)),
                ('recurrence', recurrence.fields.RecurrenceField(blank=True, null=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'doctor_profile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='patients.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
