# Generated by Django 5.2.3 on 2025-06-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_alter_encounter_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='type',
            field=models.CharField(choices=[('consultation', 'Консультация'), ('admission', 'Поступление')], max_length=20, verbose_name='Тип случая'),
        ),
    ]
