# Generated by Django 5.2.4 on 2025-08-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0003_alter_encounter_diagnosis_treatmentplan_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='encounterdiagnosis',
            unique_together=set(),
        ),
    ]
