# Generated by Django 5.2.3 on 2025-06-30 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('encounters', '0003_alter_encounter_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='type',
        ),
        migrations.AddField(
            model_name='encounter',
            name='outcome',
            field=models.CharField(blank=True, choices=[('consultation_end', 'Консультация'), ('transferred', 'Перевод в отделение')], max_length=30, null=True, verbose_name='Исход'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='transfer_to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_encounters', to='departments.department', verbose_name='Переведён в отделение'),
        ),
    ]
