# Generated by Django 5.2.4 on 2025-08-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0004_alter_encounterdiagnosis_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentplan',
            name='is_active',
        ),
    ]
