# Generated by Django 5.2.3 on 2025-06-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0004_remove_encounter_type_encounter_outcome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ['-date_start', 'is_active'], 'verbose_name': 'Случай обращения', 'verbose_name_plural': 'Случаи обращений'},
        ),
    ]
