# Generated by Django 5.2.4 on 2025-08-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0005_remove_treatmentplan_is_active'),
        ('lab_tests', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentLabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_lab_test', models.CharField(blank=True, help_text='Введите название исследования в свободной форме', max_length=200, verbose_name='Собственное исследование')),
                ('priority', models.CharField(choices=[('routine', 'Плановое'), ('urgent', 'Срочное'), ('emergency', 'Экстренное')], default='routine', max_length=20, verbose_name='Приоритет')),
                ('instructions', models.TextField(blank=True, help_text='Дополнительные инструкции по проведению исследования', verbose_name='Особые указания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_lab_tests', to='lab_tests.labtestdefinition', verbose_name='Лабораторное исследование из справочника')),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='encounters.treatmentplan', verbose_name='План лечения')),
            ],
            options={
                'verbose_name': 'Лабораторное исследование в плане лечения',
                'verbose_name_plural': 'Лабораторные исследования в плане лечения',
                'ordering': ['created_at'],
            },
        ),
    ]
