# Generated by Django 5.2.3 on 2025-06-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0005_alter_encounter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ['is_active', '-date_start'], 'verbose_name': 'Случай обращения', 'verbose_name_plural': 'Случаи обращений'},
        ),
    ]
