# Generated by Django 5.2.4 on 2025-08-15 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0006_treatmentlabtest'),
        ('instrumental_procedures', '0002_initial'),
        ('lab_tests', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Например: 'Первичное обследование', 'Контрольное обследование'", max_length=200, verbose_name='Название плана обследования')),
                ('description', models.TextField(blank=True, verbose_name='Описание плана обследования')),
                ('priority', models.CharField(choices=[('routine', 'Плановое'), ('urgent', 'Срочное'), ('emergency', 'Экстренное')], default='routine', max_length=20, verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_plans', to='encounters.encounter', verbose_name='Случай обращения')),
            ],
            options={
                'verbose_name': 'План обследования',
                'verbose_name_plural': 'Планы обследования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationLabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_lab_test', models.CharField(blank=True, help_text='Введите название исследования в свободной форме', max_length=200, verbose_name='Собственное исследование')),
                ('instructions', models.TextField(blank=True, help_text='Дополнительные инструкции по проведению исследования', verbose_name='Особые указания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examination_lab_tests', to='lab_tests.labtestdefinition', verbose_name='Лабораторное исследование из справочника')),
                ('examination_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='encounters.examinationplan', verbose_name='План обследования')),
            ],
            options={
                'verbose_name': 'Лабораторное исследование в плане обследования',
                'verbose_name_plural': 'Лабораторные исследования в планах обследования',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationInstrumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_procedure', models.CharField(blank=True, help_text='Введите название инструментального исследования в свободной форме', max_length=200, verbose_name='Собственное исследование')),
                ('instructions', models.TextField(blank=True, help_text='Дополнительные инструкции по проведению исследования', verbose_name='Особые указания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrumental_procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examination_instrumental_procedures', to='instrumental_procedures.instrumentalproceduredefinition', verbose_name='Инструментальное исследование из справочника')),
                ('examination_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumental_procedures', to='encounters.examinationplan', verbose_name='План обследования')),
            ],
            options={
                'verbose_name': 'Инструментальное исследование в плане обследования',
                'verbose_name_plural': 'Инструментальные исследования в планах обследования',
                'ordering': ['created_at'],
            },
        ),
    ]
