# Generated by Django 5.2.4 on 2025-08-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0007_examinationplan_examinationlabtest_and_more'),
        ('treatment_assignments', '0002_remove_medicationassignment_dosing_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationlabtest',
            name='custom_lab_test',
        ),
        migrations.RemoveField(
            model_name='examinationlabtest',
            name='lab_test',
        ),
        migrations.AddField(
            model_name='examinationlabtest',
            name='lab_test_assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examination_plans', to='treatment_assignments.labtestassignment', verbose_name='Назначение лабораторного исследования'),
            preserve_default=False,
        ),
    ]
