# Generated by Django 5.2.4 on 2025-08-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0008_remove_examinationlabtest_custom_lab_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationlabtest',
            name='examination_plan',
        ),
        migrations.RemoveField(
            model_name='examinationlabtest',
            name='lab_test_assignment',
        ),
        migrations.RemoveField(
            model_name='examinationplan',
            name='encounter',
        ),
        migrations.DeleteModel(
            name='ExaminationInstrumental',
        ),
        migrations.DeleteModel(
            name='ExaminationLabTest',
        ),
        migrations.DeleteModel(
            name='ExaminationPlan',
        ),
    ]
