# Generated by Django 5.2.4 on 2025-08-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0009_remove_examinationlabtest_examination_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentmedication',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='treatmentmedication',
            name='treatment_plan',
        ),
        migrations.RemoveField(
            model_name='treatmentplan',
            name='encounter',
        ),
        migrations.DeleteModel(
            name='TreatmentLabTest',
        ),
        migrations.DeleteModel(
            name='TreatmentMedication',
        ),
        migrations.DeleteModel(
            name='TreatmentPlan',
        ),
    ]
