# Generated by Django 5.2.3 on 2025-07-06 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrumental_procedures', '0001_initial'),
        ('treatment_assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentalprocedureresult',
            name='instrumental_procedure_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='treatment_assignments.instrumentalprocedureassignment', verbose_name='Назначение инструментального исследования'),
        ),
        migrations.AddField(
            model_name='instrumentalprocedureresult',
            name='result_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instrumental_procedures.instrumentalprocedureresulttype', verbose_name='Тип результата'),
        ),
    ]
