# Generated by Django 5.2.4 on 2025-07-13 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrumental_procedures', '0001_initial'),
        ('treatment_assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentalprocedureresult',
            name='instrumental_procedure_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='treatment_assignments.instrumentalprocedureassignment', verbose_name='Назначение инструментального исследования'),
        ),
        migrations.AddField(
            model_name='instrumentalprocedureresult',
            name='procedure_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='instrumental_procedures.instrumentalproceduredefinition', verbose_name='Тип исследования'),
        ),
    ]
