# Generated by Django 5.2.3 on 2025-07-04 06:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumental_procedures', '0001_initial'),
        ('treatment_assignments', '0002_alter_generaltreatmentassignment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentalProcedureResultType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название типа результата исследования')),
                ('schema', models.JSONField(help_text='Описывает поля, их типы и метки', verbose_name='Схема полей результата (JSON)')),
            ],
            options={
                'verbose_name': 'Тип результата инструментального исследования',
                'verbose_name_plural': 'Типы результатов инструментальных исследований',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentalProcedureResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_result', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата результата')),
                ('data', models.JSONField(default=dict, verbose_name='Данные результата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('instrumental_procedure_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='treatment_assignments.instrumentalprocedureassignment', verbose_name='Назначение инструментального исследования')),
                ('result_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instrumental_procedures.instrumentalprocedureresulttype', verbose_name='Тип результата')),
            ],
            options={
                'verbose_name': 'Результат инструментального исследования',
                'verbose_name_plural': 'Результаты инструментальных исследований',
                'ordering': ['-datetime_result'],
            },
        ),
    ]
