# Generated by Django 5.2.4 on 2025-09-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_management', '0005_examinationinstrumental_cancellation_reason_and_more'),
        ('instrumental_procedures', '0005_instrumentalprocedureresult_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentalprocedureresult',
            name='examination_instrumental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrumental_procedure_results', to='examination_management.examinationinstrumental', verbose_name='Назначение инструментального исследования'),
        ),
    ]
