# Generated by Django 5.2.3 on 2025-06-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование отделения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Номер отделения')),
            ],
        ),
    ]
