# Generated by Django 5.2.3 on 2025-06-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отделение', 'verbose_name_plural': 'Отделения'},
        ),
    ]
