# Generated by Django 5.2.3 on 2025-07-03 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdepartmentstatus',
            name='source_encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_transfer_records', to='encounters.encounter', verbose_name='Случай обращения-источник перевода'),
        ),
    ]
