# Generated by Django 5.2.3 on 2025-07-05 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdepartmentstatus',
            name='admission_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата поступления в отделение'),
        ),
    ]
