# Generated by Django 5.2.4 on 2025-07-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdepartmentstatus',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='patientdepartmentstatus',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивировано'),
        ),
    ]
