# Generated by Django 5.2.3 on 2025-07-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(default=11, unique=True, verbose_name='Код отделения (slug)'),
            preserve_default=False,
        ),
    ]
