# Generated by Django 5.2.3 on 2025-06-30 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_patientdepartmentstatus'),
        ('encounters', '0006_alter_encounter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdepartmentstatus',
            name='source_encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_transfer_records', to='encounters.encounter', verbose_name='Случай обращения-источник перевода'),
        ),
        migrations.AlterField(
            model_name='patientdepartmentstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает принятия'), ('accepted', 'Принят в отделение'), ('discharged', 'Выписан из отделения'), ('transferred_out', 'Переведен в другое отделение'), ('transfer_cancelled', 'Перевод отменен')], default='pending', max_length=20, verbose_name='Статус в отделении'),
        ),
    ]
