# Generated by Django 5.2.4 on 2025-08-04 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pharmacy', '0002_administrationmethod_medicationgroup_releaseform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название плана')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'План лечения',
                'verbose_name_plural': 'Планы лечения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_medication', models.CharField(blank=True, help_text='Введите название препарата, если его нет в справочнике', max_length=200, verbose_name='Собственный препарат')),
                ('dosage', models.CharField(max_length=100, verbose_name='Дозировка')),
                ('frequency', models.CharField(max_length=100, verbose_name='Частота приема')),
                ('route', models.CharField(choices=[('oral', 'Перорально'), ('intramuscular', 'Внутримышечно'), ('intravenous', 'Внутривенно'), ('subcutaneous', 'Подкожно'), ('topical', 'Наружно'), ('inhalation', 'Ингаляционно'), ('rectal', 'Ректально'), ('other', 'Другое')], default='oral', max_length=20, verbose_name='Способ введения')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Длительность')),
                ('instructions', models.TextField(blank=True, verbose_name='Особые указания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medication', verbose_name='Препарат из справочника')),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='treatment_management.treatmentplan', verbose_name='План лечения')),
            ],
            options={
                'verbose_name': 'Лекарство в плане лечения',
                'verbose_name_plural': 'Лекарства в планах лечения',
                'ordering': ['-created_at'],
            },
        ),
    ]
