# Generated by Django 5.2.4 on 2025-08-11 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите рекомендацию', verbose_name='Текст рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='treatment_management.treatmentplan', verbose_name='План лечения')),
            ],
            options={
                'verbose_name': 'Рекомендация в плане лечения',
                'verbose_name_plural': 'Рекомендации в планах лечения',
                'ordering': ['-created_at'],
            },
        ),
    ]
