# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_medication_code_medication_code_system_and_more'),
        ('treatment_management', '0002_treatmentrecommendation'),
    ]

    operations = [
        # Изменяем поле route на ForeignKey
        migrations.AlterField(
            model_name='treatmentmedication',
            name='route',
            field=models.ForeignKey(
                blank=True,
                help_text='Выберите способ введения препарата',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='pharmacy.administrationmethod',
                verbose_name='Способ введения'
            ),
        ),
    ] 