# Generated by Django 5.2.4 on 2025-08-18 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('departments', '0002_initial'),
        ('encounters', '0010_remove_treatment_models'),
        ('treatment_management', '0003_alter_treatmentmedication_route'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель плана'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='encounters.encounter', verbose_name='Случай обращения'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='patient_department_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='departments.patientdepartmentstatus', verbose_name='Статус пациента в отделении'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['patient_department_status', 'created_at'], name='treatment_m_patient_5f6a37_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['encounter', 'created_at'], name='treatment_m_encount_64109b_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['content_type', 'object_id', 'created_at'], name='treatment_m_content_255d94_idx'),
        ),
    ]
