# Generated by Django 5.2.4 on 2025-09-04 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_dosinginstruction_compatible_forms'),
        ('treatment_management', '0008_remove_treatmentmedication_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentmedication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Назначение лекарства', 'verbose_name_plural': 'Назначения лекарств'},
        ),
        migrations.AlterModelOptions(
            name='treatmentrecommendation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекомендации'},
        ),
        migrations.RemoveField(
            model_name='treatmentmedication',
            name='custom_medication',
        ),
        migrations.AddField(
            model_name='treatmentmedication',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='treatmentmedication',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отменено'),
        ),
        migrations.AddField(
            model_name='treatmentmedication',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_medications', to=settings.AUTH_USER_MODEL, verbose_name='Отменено пользователем'),
        ),
        migrations.AddField(
            model_name='treatmentmedication',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('cancelled', 'Отменено'), ('completed', 'Завершено'), ('paused', 'Приостановлено')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='treatmentrecommendation',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='treatmentrecommendation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отменено'),
        ),
        migrations.AddField(
            model_name='treatmentrecommendation',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Отменено пользователем'),
        ),
        migrations.AddField(
            model_name='treatmentrecommendation',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('cancelled', 'Отменено'), ('completed', 'Завершено'), ('paused', 'Приостановлено')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='treatmentmedication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='treatmentmedication',
            name='dosage',
            field=models.CharField(max_length=100, verbose_name='Доза'),
        ),
        migrations.AlterField(
            model_name='treatmentmedication',
            name='frequency',
            field=models.CharField(max_length=100, verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='treatmentmedication',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_medications', to='pharmacy.medication', verbose_name='Лекарство'),
        ),
        migrations.AlterField(
            model_name='treatmentmedication',
            name='route',
            field=models.CharField(max_length=100, verbose_name='Путь введения'),
        ),
        migrations.AlterField(
            model_name='treatmentmedication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='treatmentrecommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='treatmentrecommendation',
            name='text',
            field=models.TextField(verbose_name='Текст рекомендации'),
        ),
        migrations.AlterField(
            model_name='treatmentrecommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
