# Generated by Django 5.2.4 on 2025-09-04 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_dosinginstruction_compatible_forms'),
        ('treatment_management', '0009_alter_treatmentmedication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentmedication',
            name='route',
            field=models.ForeignKey(blank=True, help_text='Выберите способ введения препарата', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.administrationmethod', verbose_name='Путь введения'),
        ),
    ]
